In [ ]:
# loc[행옵션, 열옵션] : 레이블 인덱스
# iloc[행옵션, 열옵션] : 위치 인덱스
# [] : 열 레이블, 표현식(T/F 조건식, 논리식,슬라이싱, ....)

In [1]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88]
}, index=['A', 'B', 'C', 'D', 'E'])

print(df)

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [ ]:
df.loc['B', :] # df.loc['B',:]

이름    이영희
학년      2
점수     92
Name: B, dtype: object

In [3]:
df.loc['B','점수']

np.int64(92)

In [4]:
df.iloc[0,2] # 인덱스 레이블이 숫자로 되어있다면

np.int64(85)

In [9]:
df['이름'] # 열 이름

A    김철수
B    이영희
C    박민수
D    최수진
E    정우진
Name: 이름, dtype: str

In [10]:
df['A':'A'] # 식-> 지정 식 행 전체

    이름  학년  점수
A  김철수   1  85

In [11]:
df['이름' : '이름']

Empty DataFrame
Columns: [이름, 학년, 점수]
Index: []

In [14]:
df[['이름', '학년']]

    이름  학년
A  김철수   1
B  이영희   2
C  박민수   1
D  최수진   3
E  정우진   2

In [15]:
df[0 : 5]

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [16]:
df['A' : 'E']

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [ ]:
# [열이름], [열이름리스트], -> 열선택
# [식] -> 행선택
# [:]
# [조건식]

In [ ]:
# t = df['점수']
# df[t > 90]
df[ df['점수'] > 90 ]

    이름  학년  점수
B  이영희   2  92
D  최수진   3  95

In [20]:
import seaborn as sns

In [24]:
mpg = sns.load_dataset('mpg')
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
[x> 10 for x in [5, 10, 15, 20]] # 컴프리핸션

[False, False, True, True]

In [29]:
[x for x in [5, 10, 15, 20] if x > 10]

[15, 20]

In [30]:
type(df['점수'])

pandas.Series

In [31]:
pd.Series([5,10,15,20]) > 10

0    False
1    False
2     True
3     True
dtype: bool

In [33]:
mpg ['mpg']

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [ ]:
mpg ['mpg', 'weight', 'origin'] # 오류 발생, 열이름 리스트는 [[]]로 묶어야 함
mpg [['mpg', 'weight', 'origin']] # 올바른 열 선택 방법

      mpg  weight  origin
0    18.0    3504     usa
1    15.0    3693     usa
2    18.0    3436     usa
3    16.0    3433     usa
4    17.0    3449     usa
..    ...     ...     ...
393  27.0    2790     usa
394  44.0    2130  europe
395  32.0    2295     usa
396  28.0    2625     usa
397  31.0    2720     usa

[398 rows x 3 columns]

In [38]:
mpg.iloc[10]

mpg                            15.0
cylinders                         8
displacement                  383.0
horsepower                    170.0
weight                         3563
acceleration                   10.0
model_year                       70
origin                          usa
name            dodge challenger se
Name: 10, dtype: object

In [40]:
mpg.iloc[3,1] # 3행 1열 선택, 3행은 포함되지 않음

np.int64(8)

In [41]:
mpg.iloc[1:5, 1:3]

   cylinders  displacement
1          8         350.0
2          8         318.0
3          8         304.0
4          8         302.0