In [1]:
import pandas as pd

data = {
    "날짜": [
        "2025-01-01", "2025-01-02", "2025-01-03",
        "2025-02-01", "2025-02-02", "2025-02-03",
        "2025-03-01", "2025-03-02", "2025-03-03"
    ],
    "매출": [
        100, 120, None,
        200, None, 220,
        300, 320, None
    ]
}

df = pd.DataFrame(data)

df["날짜"] = pd.to_datetime(df["날짜"])

print(df)

          날짜     매출
0 2025-01-01  100.0
1 2025-01-02  120.0
2 2025-01-03    NaN
3 2025-02-01  200.0
4 2025-02-02    NaN
5 2025-02-03  220.0
6 2025-03-01  300.0
7 2025-03-02  320.0
8 2025-03-03    NaN

In [ ]:
df['월'] = df['날짜'].dt.month
df
# 시계열 결측치의 경우 이전행, 다음행, (이전행+다음행)/2, 시계열 범주의 평균or중앙값

          날짜     매출  월
0 2025-01-01  100.0  1
1 2025-01-02  120.0  1
2 2025-01-03    NaN  1
3 2025-02-01  200.0  2
4 2025-02-02    NaN  2
5 2025-02-03  220.0  2
6 2025-03-01  300.0  3
7 2025-03-02  320.0  3
8 2025-03-03    NaN  3

In [5]:
cond = (df['월'] == 1)
print(cond)

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
Name: 월, dtype: bool

In [7]:
df[df['월'] == 1]

          날짜     매출  월
0 2025-01-01  100.0  1
1 2025-01-02  120.0  1
2 2025-01-03    NaN  1

In [9]:
mean1 = (df.loc[df['월'] == 1, '매출']).mean()
mean1

np.float64(110.0)

In [10]:
mean2 = (df.loc[df['월'] == 2, '매출']).mean()
mean2

np.float64(210.0)

In [11]:
mean3 = (df.loc[df['월'] == 3, '매출']).mean()
mean3

np.float64(310.0)

In [13]:
cond = (df['매출'].isna()) & (df['월'] == 1 )
# df[cond]['매출']
df.loc[cond, '매출'] = mean1
df

          날짜     매출  월
0 2025-01-01  100.0  1
1 2025-01-02  120.0  1
2 2025-01-03  110.0  1
3 2025-02-01  200.0  2
4 2025-02-02    NaN  2
5 2025-02-03  220.0  2
6 2025-03-01  300.0  3
7 2025-03-02  320.0  3
8 2025-03-03    NaN  3

In [ ]:
cond = (df['매출'].isna()) & (df['월'] == 2 )
# df[cond]['매출']
df.loc[cond, '매출'] = mean2

In [ ]:
from sklearn.linear_model import LinearRegression

# 열x, 열y => y = ax + b 
# 열x1, 열x2, 열y -> y = ax1 + ax2 + b 
# 10 = 5 + 3*1 + 2*NaN => 결측치 -> 1

In [3]:
import pandas as pd


data = {
    "공부시간": [1, 2, 3, 4, 5, 6, 7, 8],
    "게임시간": [5, 4, 4, 3, 3, 2, 2, 1],
    "시험점수": [45, 50, None, 62, 68, None, 80, 88]
}

df = pd.DataFrame(data)

df

   공부시간  게임시간  시험점수
0     1     5  45.0
1     2     4  50.0
2     3     4   NaN
3     4     3  62.0
4     5     3  68.0
5     6     2   NaN
6     7     2  80.0
7     8     1  88.0

In [5]:
train = df[df['시험점수'].notna()]
train

   공부시간  게임시간  시험점수
0     1     5  45.0
1     2     4  50.0
3     4     3  62.0
4     5     3  68.0
6     7     2  80.0
7     8     1  88.0

In [6]:
X_train = train [['공부시간', '게임시간']]
y_train = train ['시험점수']

In [7]:
X_train

   공부시간  게임시간
0     1     5
1     2     4
3     4     3
4     5     3
6     7     2
7     8     1

In [ ]:
y_train

0    45.0
1    50.0
3    62.0
4    68.0
6    80.0
7    88.0
Name: 시험점수, dtype: float64

In [10]:

model = LinearRegression()
model.fit(X_train, y_train)
print(model.coef_)
print(model.intercept_)

[ 5.78571429 -0.60714286]
41.28571428571432

In [11]:
cond = df['시험점수'].isna()
m = df.loc[cond, ['공부시간', '게임시간']]
m

   공부시간  게임시간
2     3     4
5     6     2

In [13]:
result_y = model.predict(m)
print(result_y, type(result_y)) # 내부적 사용하는 numpy 가 결과값으로 ... numpy 학습이 필요하다

[56.21428571 74.78571429] <class 'numpy.ndarray'>

In [16]:
df.loc[cond, '시험점수'] = result_y.round(1)
df

   공부시간  게임시간  시험점수
0     1     5  45.0
1     2     4  50.0
2     3     4  56.2
3     4     3  62.0
4     5     3  68.0
5     6     2  74.8
6     7     2  80.0
7     8     1  88.0