In [1]:
import pandas as pd


# 누락값 확인 isna() 또는 isnull()을 사용한다.
# None은 python에서 값이 없는 객체
# NaN은 numpy, pandas의 숫자데이터의 결측값(None을 입력해도 NaN으로 처리됨)

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None],
    "출석": [True, True, None, True, False]
}

df = pd.DataFrame(data)

print(df) # 데이터프레임은 객체타입은 None, 숫자타입은 NaN으로 처리

print(df.isna())
print(df.isnull())

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [ ]:
df.isna().sum() # 결측치 개수 반환 x DataFrame.isna() 메서드
# 0 0 0
# 0 1 0 
# 0 0 1
# 0 0 0 
# 0 1 0

이름    0
점수    2
출석    1
dtype: int64

In [ ]:
df['점수'].isna() # Series.isna() 메서드

0    False
1     True
2    False
3    False
4     True
Name: 점수, dtype: bool

In [7]:
df

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [ ]:
cond = df['점수'].isna()
df[cond]

# df[조건식] df[size가 len(df) 같은 bool배열]

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

In [ ]:
cond = df["점수"].isna() # [False, True, False, False, True] 시리즈 반환
print(df[cond]) # df[[False, True, False, False, True]] => True인 인덱스1, 4행 출력

# 한줄의 코드로 만들면
print(df[df["점수"].isna()]) # df[조건] -> 행반환

# cond가 True 이름만 출력 => loc[] 인덱스 사용
# []연산자 : 행전체 or 열전체
# loc[]인덱스 : 행x열 조합
print(df.loc[cond, "이름"]) # df[조건] -> 행반환
print(df.loc[df["점수"].isna(), "이름"]) # df[조건] -> 행반환

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
1    이서연
4    정현우
Name: 이름, dtype: str
1    이서연
4    정현우
Name: 이름, dtype: str

In [10]:
print(df.isna().any()) # 데이터프레임 열에 누락값이 하나라도 있으면 True

print(df.isna().all()) # 데이터프레임 열이 모두 누락값이면 True

이름    False
점수     True
출석     True
dtype: bool
이름    False
점수    False
출석    False
dtype: bool

In [11]:
df2 = df.dropna()
df2

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True

In [13]:
df3 = df.dropna(subset=['출석'])
df3

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
3  최유진  75.0   True
4  정현우   NaN  False

In [14]:
df4 = df.dropna(subset=['점수'])
df4

    이름    점수    출석
0  김민준  85.0  True
2  박지훈  90.0  None
3  최유진  75.0  True

In [ ]:
df4 = df.dropna(subset=df.columns) # 기본값 
df4

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True

In [16]:
df2 = df
display(df)
df2['점수'] = df['점수'].fillna(100)
display(df2)

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

In [17]:
avg = df['점수'].mean()

In [19]:
df2 = df.copy()
df2['점수'] = df2['점수'].fillna(round(avg, 1))
df2

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

In [20]:
# 평균값으로 누락값 대체
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None]
}

df = pd.DataFrame(data)
df

    이름    점수
0  김민준  85.0
1  이서연   NaN
2  박지훈  90.0
3  최유진  75.0
4  정현우   NaN

In [21]:
mean_score = df["점수"].mean()
df["점수"] = df["점수"].fillna(mean_score)
print(df)

    이름         점수
0  김민준  85.000000
1  이서연  83.333333
2  박지훈  90.000000
3  최유진  75.000000
4  정현우  83.333333

In [23]:
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "성별": ["M", "F", None, "F", None] 
}

df = pd.DataFrame(data)

mode_gender = df["성별"].mode()[0]

df["성별"] = df["성별"].fillna(mode_gender)

print(df)

    이름 성별
0  김민준  M
1  이서연  F
2  박지훈  F
3  최유진  F
4  정현우  F