In [1]:
import pandas as pd

df = pd.DataFrame({
    "이름": ["철수", "영희"],
    "국어": [80, 90],
    "영어": [70, 95],
    "수학": [90, 85]
})

display(df)

   이름  국어  영어  수학
0  철수  80  70  90
1  영희  90  95  85

In [2]:
df_melt = df.melt(
    id_vars="이름",       # 그대로 유지할 열, 이름은 각 행의 대상을 구분하기 위해 그대로 놔둔다
    var_name="과목",      # 기존 열 이름을 저장할 열
    value_name="점수"     # 기존 열의 값을 저장할 열
)

display(df_melt)

   이름  과목  점수
0  철수  국어  80
1  영희  국어  90
2  철수  영어  70
3  영희  영어  95
4  철수  수학  90
5  영희  수학  85

In [3]:
df_pivot = df_melt.pivot(index = '이름', columns = '과목', values = '점수')
df_pivot

과목  국어  수학  영어
이름
영희  90  85  95
철수  80  90  70

In [4]:
display(df)

   이름  국어  영어  수학
0  철수  80  70  90
1  영희  90  95  85

In [6]:
result = df_pivot.reset_index()
result

과목  이름  국어  수학  영어
0   영희  90  85  95
1   철수  80  90  70

In [7]:
df2 = pd.DataFrame({
    "이름": ["철수", "영희"],
    "국어": [80, 90],
    "영어": [70, 95],
    "수학": [90, 85]
})

df2

   이름  국어  영어  수학
0  철수  80  70  90
1  영희  90  95  85

In [9]:
df2 = pd.DataFrame({
    "이름": ["철수", "철수", "철수", "철수", "영희", "영희", "영희"],
    "과목": ["국어", "국어", "영어", "수학", "국어", "영어", "수학"],
    "점수": [80, 50, 70, 90, 90, 95, 85]
})

display(df2)

   이름  과목  점수
0  철수  국어  80
1  철수  국어  50
2  철수  영어  70
3  철수  수학  90
4  영희  국어  90
5  영희  영어  95
6  영희  수학  85

In [49]:
df3 = df2.pivot_table(index = '이름', columns = '과목', values = '점수', aggfunc = 'max')

In [50]:
df4 = df3.reset_index()
df4

과목  이름  국어  수학  영어
0   영희  90  85  95
1   철수  80  90  70