In [1]:
# 인덱스 조작(레이블 인덱스. 위치값 아니다)

# 현재 인덱스를 확인
import pandas as pd

df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

print(df)

print(df.index)

    이름  점수
0  김민준  85
1  이서연  90
2  박지훈  75
RangeIndex(start=0, stop=3, step=1)

In [2]:
print(df.index.tolist()) # 레이블 인덱스 값을 리스트로 반환
print(df.index.name) # 레이블 인덱스 이름, 없으면 None

[0, 1, 2]
None

In [3]:
# 인덱스 이름 설정
df.index.name = "학생구분"
print(df)
# 인덱스 변경
df.index = ["학생1", "학생2", "학생3"]

print(df)

       이름  점수
학생구분
0     김민준  85
1     이서연  90
2     박지훈  75
      이름  점수
학생1  김민준  85
학생2  이서연  90
학생3  박지훈  75

In [4]:
# 열을 인덱스로 변경
df = pd.DataFrame({
    "학생ID": [101, 102, 103],
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

print(df)

df2 = df.set_index("학생ID") # 변경된 데이터프레임을 반환

print(df2)

# 반환없이 원본의 인덱스를 변경  inplace=True 매개값 추가
df.set_index("학생ID", inplace=True) # 컬럼이름이 인덱스이름이 된다.
df

   학생ID   이름  점수
0   101  김민준  85
1   102  이서연  90
2   103  박지훈  75
       이름  점수
학생ID
101   김민준  85
102   이서연  90
103   박지훈  75

       이름  점수
학생ID
101   김민준  85
102   이서연  90
103   박지훈  75

In [5]:
# 인덱스를 열로 변경
df = pd.DataFrame({
    "학생ID": [101, 102, 103],
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

print(df)

df2 = df.reset_index(names="번호") # names생략시 인덱스이름이 기본값, 이름이 없으면 "index"

print(df2)

   학생ID   이름  점수
0   101  김민준  85
1   102  이서연  90
2   103  박지훈  75
   번호  학생ID   이름  점수
0   0   101  김민준  85
1   1   102  이서연  90
2   2   103  박지훈  75

In [6]:
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"]
}, index=[10, 20, 30])

print(df)

df2 = df.reset_index(drop=True) # reset_index의 기본값은 인덱스를 열로 이동인데, drop=True이면 삭제
print(df2)

     이름
10  김민준
20  이서연
30  박지훈
    이름
0  김민준
1  이서연
2  박지훈

In [7]:
df.reset_index(inplace=True) # 기본값 False 원본변경 x
df

   index   이름
0     10  김민준
1     20  이서연
2     30  박지훈

In [8]:
# 인덱스 정렬
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"]
}, index=[30, 10, 20])

print(df)

df2 = df.sort_index()

print(df2)

     이름
30  김민준
10  이서연
20  박지훈
     이름
10  이서연
20  박지훈
30  김민준